version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: mysql
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 123456
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    ports:
      - 53306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      #- /etc/timezone:/etc/timezone
      #- /etc/localtime:/etc/localtime
