version: "3"
services:
  mysql:
    hostname: mysql
    image: mysql:8.0
    container_name: mysql-8.0
    privileged: true
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --max_connections=2000 --max_allowed_packet=64M
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql-8.0-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      caseor_bridge:
        ipv4_address: 192.168.123.80

  nacos:
    hostname: nacos
    image: nacos/nacos-server:2.0.3
    container_name: nacos-2.0.3
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.123.80
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=UTC
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      caseor_bridge:
        ipv4_address: 192.168.123.88

networks:
  caseor_bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 255.255.255.0/16

volumes:
  mysql-8.0-data: {}